server:
  port: 9000

# default
spring:
  profiles:
    active: local
  application:
    name: gateway-service
    version: 0.0.1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19010/eureka/

---
spring:
  config:
    activate:
      on-profile: local

  routes:
    - id: first-service
      uri: lb://MY-FIRST-SERVICE
      predicates:
        - Path=/first-service/**

---
spring:
  config:
    activate:
      on-profile: dev

# ...
---
spring:
  config:
    activate:
      on-profile: prod